import { Certification } from '@/types'

export const mockCertifications: Certification[] = [
  {
    id: '1',
    name: 'AWS Certified Solutions Architect - Professional',
    issuingOrganization: 'Amazon Web Services',
    issueDate: new Date('2023-06-15'),
    expirationDate: new Date('2026-06-15'),
    credentialId: 'AWS-SAP-2023-001',
    credentialUrl: 'https://credly.com/badges/aws-sap-professional',
    description: 'Advanced certification for designing distributed applications and systems on AWS platform.',
    category: 'cloud',
    level: 'professional',
    status: 'active',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/2d84e428-9078-49b6-a804-13c15383d0de/image.png',
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2023-06-15'),
  },
  {
    id: '2',
    name: 'Certified Kubernetes Administrator (CKA)',
    issuingOrganization: 'Cloud Native Computing Foundation',
    issueDate: new Date('2023-09-20'),
    expirationDate: new Date('2026-09-20'),
    credentialId: 'CKA-2023-09-001',
    credentialUrl: 'https://training.linuxfoundation.org/certification/verify',
    description: 'Hands-on certification for Kubernetes cluster administration and troubleshooting.',
    category: 'devops',
    level: 'professional',
    status: 'active',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/8b8ed108-e77d-4396-ac59-2504583b9d54/cka_from_cncftrainingLF.png',
    createdAt: new Date('2023-09-20'),
    updatedAt: new Date('2023-09-20'),
  },
  {
    id: '3',
    name: 'Google Cloud Professional Data Engineer',
    issuingOrganization: 'Google Cloud',
    issueDate: new Date('2022-11-10'),
    expirationDate: new Date('2024-11-10'),
    credentialId: 'GCP-PDE-2022-11-001',
    credentialUrl: 'https://cloud.google.com/certification/data-engineer',
    description: 'Professional certification for designing and building data processing systems on Google Cloud.',
    category: 'data',
    level: 'professional',
    status: 'expiring_soon',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/9e951be7-d1c8-4c9c-bb37-dd4b4b6d20a8/gcp-professional-data-engineer.png',
    createdAt: new Date('2022-11-10'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: '4',
    name: 'Certified Information Systems Security Professional (CISSP)',
    issuingOrganization: '(ISC)² - International Information System Security Certification Consortium',
    issueDate: new Date('2021-03-15'),
    expirationDate: new Date('2024-03-15'),
    credentialId: 'CISSP-2021-03-001',
    credentialUrl: 'https://www.isc2.org/Certifications/CISSP',
    description: 'Advanced security certification covering eight domains of cybersecurity knowledge.',
    category: 'security',
    level: 'expert',
    status: 'expired',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/e4cb9a47-9b6f-4e2e-8b3c-dfde6e48b0b3/cissp.png',
    createdAt: new Date('2021-03-15'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: '5',
    name: 'Microsoft Certified: Azure Developer Associate',
    issuingOrganization: 'Microsoft',
    issueDate: new Date('2023-12-05'),
    expirationDate: new Date('2025-12-05'),
    credentialId: 'AZ-204-2023-12-001',
    credentialUrl: 'https://learn.microsoft.com/en-us/certifications/azure-developer/',
    description: 'Certification for developing cloud applications and services on Microsoft Azure.',
    category: 'cloud',
    level: 'associate',
    status: 'active',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/63316b60-f62d-4e51-aacc-c23cb850089c/azure-developer-associate-600x600.png',
    createdAt: new Date('2023-12-05'),
    updatedAt: new Date('2023-12-05'),
  },
  {
    id: '6',
    name: 'Project Management Professional (PMP)',
    issuingOrganization: 'Project Management Institute',
    issueDate: new Date('2022-08-20'),
    expirationDate: new Date('2025-08-20'),
    credentialId: 'PMP-2022-08-001',
    credentialUrl: 'https://www.pmi.org/certifications/project-management-pmp',
    description: 'Global standard for project management certification demonstrating experience and skill.',
    category: 'management',
    level: 'professional',
    status: 'active',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/260e36dc-d100-45c3-852f-9d8063fa71e8/pmp-600px.png',
    createdAt: new Date('2022-08-20'),
    updatedAt: new Date('2022-08-20'),
  },
  {
    id: '7',
    name: 'Terraform Associate',
    issuingOrganization: 'HashiCorp',
    issueDate: new Date('2023-04-12'),
    expirationDate: new Date('2025-04-12'),
    credentialId: 'TERRAFORM-ASSOC-2023-04-001',
    credentialUrl: 'https://www.credly.com/badges/terraform-associate',
    description: 'Infrastructure as Code certification covering Terraform concepts and best practices.',
    category: 'devops',
    level: 'associate',
    status: 'active',
    verificationStatus: 'pending',
    logo: 'https://images.credly.com/size/340x340/images/85b9cfc4-257a-4742-878c-4f7ab4a2631b/HashiCorp-Terraform-Associate.png',
    createdAt: new Date('2023-04-12'),
    updatedAt: new Date('2023-04-12'),
  },
  {
    id: '8',
    name: 'React Developer Certification',
    issuingOrganization: 'Meta (Facebook)',
    issueDate: new Date('2023-10-30'),
    credentialId: 'META-REACT-2023-10-001',
    credentialUrl: 'https://developers.facebook.com/certification/',
    description: 'Certification demonstrating proficiency in React.js development and modern frontend practices.',
    category: 'development',
    level: 'professional',
    status: 'active',
    verificationStatus: 'unverified',
    logo: 'https://images.credly.com/size/340x340/images/4f5b4f71-b92e-4a16-83b1-db1b6a7de69a/meta-certified-react-developer.png',
    createdAt: new Date('2023-10-30'),
    updatedAt: new Date('2023-10-30'),
  },
  {
    id: '9',
    name: 'Adobe Certified Expert - UX Design',
    issuingOrganization: 'Adobe',
    issueDate: new Date('2022-05-18'),
    expirationDate: new Date('2024-05-18'),
    credentialId: 'ACE-UX-2022-05-001',
    credentialUrl: 'https://www.adobe.com/training-and-certification.html',
    description: 'Expert-level certification in user experience design using Adobe Creative Suite.',
    category: 'design',
    level: 'expert',
    status: 'expiring_soon',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/6b7e7123-5f4f-4c1d-abfc-4c2e9c2d8d4a/adobe-certified-expert-ux.png',
    createdAt: new Date('2022-05-18'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: '10',
    name: 'MongoDB Certified Developer Associate',
    issuingOrganization: 'MongoDB University',
    issueDate: new Date('2023-07-25'),
    expirationDate: new Date('2026-07-25'),
    credentialId: 'MONGODB-DEV-2023-07-001',
    credentialUrl: 'https://university.mongodb.com/certification',
    description: 'Certification demonstrating skills in MongoDB database development and administration.',
    category: 'data',
    level: 'associate',
    status: 'active',
    verificationStatus: 'verified',
    logo: 'https://images.credly.com/size/340x340/images/5a8af1e5-6ea6-4d8a-a031-8b55e4d92ebe/MongoDB_Certified_Developer_Associate.png',
    createdAt: new Date('2023-07-25'),
    updatedAt: new Date('2023-07-25'),
  },
]